In [1]:
import git
import numpy as np
import pandas as pd
import colour as color

C:\Users\joshua.waldbieser\.conda\envs\rkngh_stress\Lib\site-packages\colour\utilities\verbose.py:322: ColourUsageWarning: "Matplotlib" related API features are not available: "No module named 'matplotlib'".
See the installation guide for more information: https://www.colour-science.org/installation-guide/
  warn(*args, **kwargs)  # noqa: B028


In [2]:
repo = git.Repo('.', search_parent_directories = True)
root = repo.working_tree_dir

In [3]:
data_consol = pd.read_csv(root + '//data/data_consol.csv')

X = data_consol.filter(regex="^[0-9]+$")

In [4]:
X

350     351     352     353     354     355     356     357     358  \
0    0.0149  0.0190  0.0355  0.0685  0.1215  0.1519  0.2037  0.3586  0.5415   
1    0.0064  0.0000  0.0210  0.0517  0.0597  0.1334  0.2423  0.3313  0.4761   
2    0.3493  0.4840  0.5444  0.6273  0.8005  0.9364  1.0934  1.3867  1.6424   
3    0.0000  0.0000  0.0755  0.1990  0.3258  0.5017  0.7001  0.8715  1.0811   
4    1.8903  1.7416  1.6799  1.6486  1.6089  1.6564  1.7468  1.7962  1.9342   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
393  0.0277  0.0814  0.1449  0.2272  0.3338  0.4479  0.5798  0.7548  0.9016   
394  0.0000  0.0306  0.0977  0.1766  0.3017  0.4502  0.6091  0.7550  0.9012   
395  0.0927  0.1349  0.2236  0.3454  0.4901  0.6669  0.8636  1.0642  1.2472   
396  0.0403  0.0937  0.2195  0.4104  0.6620  0.8873  1.1088  1.3659  1.6127   
397  1.8541  2.0236  2.2213  2.4162  2.5835  2.7084  2.8310  3.0186  3.2705   

        359  ...    2491    2492    2493    2494    2495    2496    2497  \
0    0.7367  ...  5.8697  5.8376  5.7974  5.7766  5.7706  5.7443  5.6973   
1    0.6624  ...  5.1720  5.1677  5.1699  5.1577  5.1343  5.1057  5.0707   
2    1.8620  ...  6.4096  6.3448  6.2689  6.2412  6.2523  6.2632  6.2745   
3    1.3237  ...  6.6249  6.5863  6.5509  6.5473  6.5708  6.5930  6.6168   
4    2.1402  ...  7.0544  7.0439  7.0345  7.0123  6.9796  6.9493  6.9193   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
393  1.0292  ...  6.1086  6.0850  6.0597  6.0525  6.0597  6.0377  5.9807   
394  1.0436  ...  6.1823  6.1724  6.1661  6.1629  6.1629  6.1639  6.1654   
395  1.4086  ...  6.8613  6.8135  6.7665  6.7577  6.7804  6.7733  6.7303   
396  1.8420  ...  5.5237  5.5030  5.4801  5.4724  5.4769  5.4659  5.4362   
397  3.5517  ...  7.5242  7.5217  7.5250  7.5383  7.5607  7.5792  7.5940   

       2498    2499    2500  
0    5.6253  5.5118  5.4073  
1    5.0383  5.0112  4.9879  
2    6.2772  6.2648  6.2492  
3    6.6186  6.5797  6.5435  
4    6.9072  6.9241  6.9467  
..      ...     ...     ...  
393  5.9227  5.8698  5.8242  
394  6.1710  6.1847  6.1954  
395  6.6861  6.6439  6.6159  
396  5.4070  5.3811  5.3618  
397  7.6026  7.6041  7.5988  

[398 rows x 2151 columns]

In [28]:
color.SpectralDistribution(data = X)

SpectralDistribution([], shape=(0, 2), dtype=float64,
                     CubicSplineInterpolator,
                     {},
                     Extrapolator,
                     {'method': 'Constant', 'left': None, 'right': None})

In [40]:
sd_0 = color.SpectralDistribution(data = X.iloc[0])
sd_0

SpectralDistribution([[  3.50000000e+02,   1.49000000e-02],
                      [  3.51000000e+02,   1.90000000e-02],
                      [  3.52000000e+02,   3.55000000e-02],
                      ..., 
                      [  2.49800000e+03,   5.62530000e+00],
                      [  2.49900000e+03,   5.51180000e+00],
                      [  2.50000000e+03,   5.40730000e+00]],
                     SpragueInterpolator,
                     {},
                     Extrapolator,
                     {'method': 'Constant', 'left': None, 'right': None})

In [57]:
print(color.colorimetry.sd_to_XYZ(sd_0))
print(color.colorimetry.sd_to_XYZ(sd_0)/max(color.colorimetry.sd_to_XYZ(sd_0)))
print(color.colorimetry.sd_to_XYZ(sd_0, use_practice_range=True))

[ 1227.0137249   1491.98548152   641.9990028 ]
[ 0.82240326  1.          0.43029842]
[ 1227.0137249   1491.98548152   641.9990028 ]


In [65]:
X_vis = X.loc[:, '360':'780']
sd_0_vis = color.SpectralDistribution(data = X.iloc[0])
print(color.colorimetry.sd_to_XYZ(sd_0_vis))

[ 1227.0137249   1491.98548152   641.9990028 ]


Things that didn't change results: use_practice_range, method, manually restricting the data to wvs 360-780

In [68]:
print(color.colorimetry.sd_to_XYZ(sd_0))
print(color.colorimetry.sd_to_XYZ(sd_0, k=1))
print(color.colorimetry.sd_to_XYZ(sd_0, k=10))
print(color.colorimetry.sd_to_XYZ(sd_0, k=100))

[ 1227.0137249   1491.98548152   641.9990028 ]
[ 1311.14657369  1594.28669165   686.01905239]
[ 13111.46573691  15942.86691649   6860.1905239 ]
[ 131114.65736907  159428.66916488   68601.90523902]
